version: '3.9'

services:
  nginx:
    image: umputun/nginx-le:latest

    links:
      - wordpress

    hostname: nginx
    restart: always

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

    volumes:
      - ./etc/ssl:/etc/nginx/ssl
      - ./etc/service.conf:/etc/nginx/service.conf
      - ./data/html:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    environment:
      - TZ=Europe/Moscow
      - LETSENCRYPT=true
      - LE_EMAIL=${LE_EMAIL}
      - LE_FQDN=${LE_FQDN}

  mysql:
    image: mariadb
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: db
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
    restart: always

  wordpress:
    image: wordpress:php7.3-fpm-alpine
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: db
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_USER_PASSWORD}
      WORDPRESS_TABLE_PREFIX: wp_
    links:
      - mysql
    volumes:
      - ./data/html:/var/www/html
    restart: always
