name: Ansible

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  remote:
    runs-on: ubuntu-latest
    steps:
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ansible.yml
          directory: ansible
          key: ${{ secrets.SSH_KEY }}
          inventory: |
            [web_server]
            ${{ secrets.HOST }}
