name: Ansible

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  remote:
    name: 'Ansible'
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2

      - id: host
        env:
          SSH: ${{ secrets.SSH_KEY }}
        run: |
            echo ${{ secrets.HOST }} >> ansible/hosts
            echo "$SSH" > ansible/key.pem
            chmod 400 ansible/key.pem
            cat ansible/key.pem
      - name: Ansible
        uses: saubermacherag/ansible-playbook-docker-action@v1.3
        with:
          playbookName: 'ansible/ansible.yml'
          inventoryFile: 'ansible/hosts'
          keyFile: 'ansible/key.pem'
          extraVars: "USER=${{ secrets.USER }}"
