name: deply

on:
  workflow_run:
    workflows:
      - deply
    types: 
      - completed
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]

  workflow_dispatch:

jobs:
  remote:
    name: 'deploy'
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Start Deployment
      uses: wshihadeh/docker-deployment-action@master
      with:
        remote_docker_host: ${{ secrets.HOST }}
        ssh_private_key: ${{ secrets.SSH_KEY_RSA }}
        ssh_public_key: ${{ secrets.SSH_KEY_PUB }}
        deployment_mode: docker-compose
        copy_stack_file: true
        deploy_path: ~/
        stack_file_name: docker-compose.yml
        pull_images_first: true
        args: ps
