name: deply

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  remote:
    name: 'deploy'
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      
    - id: host
      env:
        SSH: ${{ secrets.SSH_KEY }}
      run: |
        echo "$SSH" > ~/key.pem
        chmod 400 ~/key.pem
        cat ~/key.pem

    - name: Start Deployment
      uses: wshihadeh/docker-deployment-action@master
      with:
        remote_docker_host: ${{ secrets.HOST }}
        ssh_private_key: '~/key.pem'
        ssh_public_key: ${{ secrets.SSH_PUB_KEY }}
        deployment_mode: docker-compose
        copy_stack_file: true
        deploy_path: ~/
        stack_file_name: docker-compose.yml
        pull_images_first: true
