name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands to set env
        uses: appleboy/ssh-action@master
        env: 
          FOO: ${{ secrets.TEST }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USER }}
          key: ${{ secrets.SSH_KEY }}
          envs: FOO,BAR,SHA 
          script: | 
            echo TEST=${{ secrets.FOO }} > .env
