name: set env

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands to set env
        uses: appleboy/ssh-action@master
        env: 
          LE_EMAIL: ${{ secrets.LE_EMAIL }}
          LE_FQDN: ${{ secrets.LE_FQDN }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USER }}
          key: ${{ secrets.SSH_KEY }}
          envs: LE_EMAIL, LE_FQDN
          script: | 
            echo LE_EMAIL=$LE_EMAIL > .env
            echo LE_FQDN=$LE_FQDN >> .env
